### ISSUE TITLE
Админка. Разные наборы полей для разных задач

### ISSUE THREAD

**Issue by ZaiSL** [joostina/joostina#101]
Например, есть задачи "добавление пользователя" и "редактирование пользователя". Было бы логично при добавлении пользователя не показывать строчки "Дата регистрации" и "Последнее посещение". 
Может, получится придумать какое-то простое решение?

**Comment by xboston** [comment]
Не вопрос, создение и редактирование объекта - это изначально разные задачи, можно добавиь небольшую абстракцию что бы скрывать часть полей в том или ином случае

**Comment by xboston** [comment]
Реализовано в коммите ac664220d44055729f08086df8a3961a1d3d97fb
Использовать:

```
'email' => array(
    'name' => 'email адрес',
    'editable' => true,
    'in_admintable' => true,
    'html_edit_element' => 'edit',
    'html_table_element' => 'value',
   'hide_on'=>'edit',
)
```

hide_on может принимать значения edit и create соответсвенно
