### ISSUE TITLE
Улучшить метод find в моделях

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#114]
Фишка вот в чем. Предположим я делаю так:

Модель->поле = joosRequest::post()
Модель->поле2 = joosRequest::post()
Модель->find()

Иногда плохие пользователи эти поля могут не заполнить, в результате поле и поле2 равны NULL. В SQL-запрос они не попадут, но SQL-запрос все равно будет выполнен, и будет выполнено что-то типа этого

SELECT \* FROM таблица WHERE 

И после WHERE идет пустота. Запрос падает, все плохо. Может там как-нибудь предусмотреть возможность подсчета, что если полей нет, которые будут участвовать в запросе, то выдавать false. Аналогично фикс find_cache()

**Comment by xboston** [comment]
Отлично, добавлю проверки

**Comment by xboston** [comment]
Добавил проверки, а что лучше делать когда ошибка в параметрах - выдавать false или бросать исключение?
