### ISSUE TITLE
Возврат объекта в контроллере

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#115]
Контроллер, а в частности аяксовый, должен для выдачи результатов всегда делать return array(xxx => zzz). Но что если разрешить возвращать не только массивы, но еще и объекты, в том числе объекты моделей. То есть если возвращен объект, то убирать оттуда поля начинающиеся с _ и конвертировать его в массив. Ну или как-нибудь так.

**Comment by xboston** [comment]
А в чем прикол?
Что это даст в плане удобства и гибкости?

**Comment by deadkrolik** [comment]
ну, типа 

$model = new Model;
$model->load(joosRequest::post('id'));
return $model;

**Comment by xboston** [comment]
Нее, н еочень хороший вариант в плане дальшнейшего внедрения шаблонизаторов и обработки переменных.
В вывод все переменные должны иметь имя, и написать <h1><?php echo $module->title ?></h1> при таком расскладе не получится, только через массивы.

Большинство обновлений в современных фреймворках кстати как раз делают что бы контроллер возвращал всегда массив, и элементы этого массива напрямую передаются в представления, всё как у нас уже сейчас реализовано.

**Comment by deadkrolik** [comment]
Окей, предположим только аякс?

Да и в конце концов, преобразовать объект в массив не так и сложно. Любое поле имеет имя и значение.

**Comment by xboston** [comment]
А в чем плюс делать такое для аякс-режима?
В чем профит добавлять еще одну проверку на тип возвращаемого результата, если такой тип будет довольно редко встречаться, но добавит в систему ще одну проверку?

Можно добавить некую функцию которая будет преобразовывать объект в массив и делать:
return Array::from_obj( $model );

**Comment by deadkrolik** [comment]
Скучный ты :)
