### ISSUE TITLE
exit и die

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#122]
В классе базы данных сейчас встречается вызов exit, если произошла ошибка подключения. Может стоит делать это исключением? Кроме того унифицировать как-то эти два по сути одинаковых метода выхода из скрипта, чтобы хотя бы простым поиском мы всегда смогли найти все места, где мы не проверяем существование константы _JOOS_CORE, а именно прекращаем работу скрипта. В классе joosPages используется die, предлагаю заменить его на exit.

**Comment by xboston** [comment]
В шапках файла переделал на exit, всё равно там die ничего не пишет
