### ISSUE TITLE
Класс почты

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#123]
Есть нормальный https://github.com/cnicodeme/PHP5-SimpleMail (там нужна пара доделок для русского языка) возможно просто создать еще один метод в существующем joosMail (типа html_mail).

**Comment by xboston** [comment]
Готово

**Comment by deadkrolik** [comment]
Небольшое ревью:

Лучше смотреть если is_array($to), то подставлять прямо его, а иначе уже оборачивать конструтором массива.
Строка 42 перекрывает строку 41.
From лучше оборачивать в красивые тэги "Отправитель <почта>".
Взять мои фиксы и добавить туда.

**Comment by xboston** [comment]
Доработал, с пос полей From надо поэкспериментировать, там иногда странные дела получаются если указывать не только email
