### ISSUE TITLE
Починить системные компоненты (параметры, категории, метатэги и т.п.)

### ISSUE THREAD

**Issue by ZaiSL** [joostina/joostina#14]
Т.е. те компоненты, которые интегрируются в другие.
Слетела привязка меню компонента... дальше не тестила во избежании нервного срыва)
Скрины:
![Было](http://dl.dropbox.com/u/4947639/misc/bugs_images/14_1.png)
![Стало](http://dl.dropbox.com/u/4947639/misc/bugs_images/14_2.png)

**Comment by xboston** [comment]
Часть починил, там кодировка файлов покоцалась местами.

**Comment by xboston** [comment]
Кодировку в мета-тэгах починил

**Comment by ZaiSL** [comment]
Главный косяк в том, что субменю пропало( Сейчас попробую вернуть всё

**Comment by ZaiSL** [comment]
Вернула везде меню
