### ISSUE TITLE
Расположение библиотек

### ISSUE THREAD

**Issue by ZaiSL** [joostina/joostina#25]
Сторонние библиотеки в vendors нужно закидывать в директории с именем == имени вендора. Иначе весь смысл теряется.
Но я в тысячный раз повторюсь - отдельная папка для вендоров - это большая головная боль (мне вот, например, эпически неудобно). Лучше сделать пустую папку с таким именем в `app`, чтобы в процессе разработки сайта можно было докидывать нужные либы уже туда, не трогая директории системы. Ну и, соответственно, сделать метод для подключения библиотек оттуда.

**Comment by xboston** [comment]
Поддерживаю вынесение библиотек вендоров в каталог проекта, займусь

**Comment by xboston** [comment]
Часть перенёс, как работу всех библиотек проверю и пропишу примеры использования - тикет закрою

**Comment by xboston** [comment]
Работает всё так же, только физический путь изменился:
Синтаксис: joosCore::path('example', 'lib-vendor','vendor_name'); результат:
[JPATH_BASE]/app/vendors/vendor_name/example/example.php
