### ISSUE TITLE
Шаблон панели управления (  )

### ISSUE THREAD

**Issue by xboston** [joostina/joostina#57]
Ирин, буду защищаться, но кажется так выглядит приятнее
![](http://img.picsa.ru/pictures/0/000/092/521/92521.png)
чем
![](http://img.picsa.ru/pictures/0/000/092/522/92522.png)
![](http://img.picsa.ru/pictures/0/000/092/523/92523.png)

**Comment by ZaiSL** [comment]
Не знаю пока
