### ISSUE TITLE
Parse error: syntax error, unexpected ':'

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [joostina/joostina#69]
!ob_get_level() ? : ob_end_clean(); в 71 и 90 строке \core\exception.php 
Так  !ob_get_level() ? null : ob_end_clean(); работает.

То-же самое W:\html\joostina2\www\core\autoloader.php on line 113

**Comment by xboston** [comment]
Необходимо php > 5.3

**Comment by xboston** [comment]
Добавил в файл README необходимое требование в php > 5.3
