### ISSUE TITLE
Непонятности в инсталляторе

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [joostina/joostina#70]
В настройках бд два одинаковых названия полей "Название базы данных", хотя одно из них предназначается для хоста.

**Comment by Arkadiy-Sedelnikov** [comment]
Короче маялся, маялся, не запустил. Морду вывел а от админки нет пароля, а новый пользователь не создается.

**Comment by xboston** [comment]
admin / 123456 , универсально ;)

**Comment by Arkadiy-Sedelnikov** [comment]
Странно, но пробовал, что-то не пошло, с морды после ввода логина ничего не меняется, а http://joostina2/admin весь в ошибках и ничего не показывает.

**Comment by xboston** [comment]
Поля переименовал, установщик обновил
