### ISSUE TITLE
Не выводить пароль в форме редактирования пользователя

### ISSUE THREAD

**Issue by ZaiSL** [joostina/joostina#8]
... в админке. Выводить просто пустое поле. Если вводится новый пароль - тогда уже обрабатывать.
![Скрин](http://dl.dropbox.com/u/4947639/misc/bugs_images/8.png)

**Comment by xboston** [comment]
Добавить:
<code>
    public function before_store() {
        parent::before_store();

```
    $new_password = mosGetParam($_POST, 'new_password');

    if (trim($new_password) != '') {
        $this->password = User::prepare_password($new_password);
    }
}
```

</code>
