### ISSUE TITLE
Модули - единообразие с компонентами

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#86]
Никаких require_once в модулях. Модули тоже должны быть классами, шаблоны должны вызываться по аналогии с компонентами return array() и все. Предусмотреть возможность для модулей получать параметры к вызванному сейчас компоненту (которые пришли через router). Единый родительский класс для модулей.

**Comment by ZaiSL** [comment]
> Предусмотреть возможность для модулей получать параметры к вызванному сейчас компоненту (которые пришли через router)

Я такое где-то реализовывала.. а на каком проекте - не помню( Удобно - не нужно специально передавать данные в модуль, так как у него уже есть всё то, чтобы вернул метод контроллера. Поддерживаю, вопчем. По остальному - тоже).

**Comment by ZaiSL** [comment]
Готово
