### ISSUE TITLE
Класс базы данных - методы с кэшем

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#87]
Класс БД должен содержать все методы для работы с кэшем - get_list_cache, find_cache, load_object_list_cache.

**Comment by xboston** [comment]
Часть уже есть:
get_list_cache: https://github.com/joostina/joostina/blob/master/core/libraries/database.php#L1677
find_cache: https://github.com/joostina/joostina/blob/master/core/libraries/database.php#L1833

load_object_list_cache в ожидании ;)

**Comment by xboston** [comment]
load_object_list_cache добавлен в 580d9b9f182de19ba5d528fcade59154b94e40b0
