### ISSUE TITLE
Переработать модель modelUsersSession

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#88]
Там всего 4 метода, но каша в коде жуткая. Наверняка еще с мамбы код остался. Надо избавиться от методов insert_object, get_num_rows. Нелогичное указание $this->_tbl, _db и прочих. Нелогичное использование uniqid(). Проверка неудачной вставки объекта не нужна, класс БД все равно умрет.

**Comment by deadkrolik** [comment]
И еще от метода update_object. Больше оно нигде не используется.

**Comment by deadkrolik** [comment]
И метода stderr

**Comment by xboston** [comment]
Код почищен, максимум мусора выкинуто, но код еще надо документировать и оптимизировать по структуре.

update_object убирать из системы нельзя, это важный системный ход работы с данными.

**Comment by deadkrolik** [comment]
Тогда в PDO класс надо не забыть внести эти два метода insert_object и update_object. Их там сейчас нет.
