### ISSUE TITLE
Некоторые замечания по коду

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#97]
---

core/libraries/file.php
Конструкция 
        if (!joosFile::exists($filename)) {
            throw new joosFileLibrariesException('Файл :file не существует', array(':file' => $filename));
        }
вполне может быть заменена на вызов отдельной функции, вроде $this->exception_if_file_not_exists();

---

return unlink((string) $filename);
Выдаст варнинг, если не получится удалить. Надо бы собачку или как-то ловить варнинги.

---

make_safe_name
В последнем регулярном выражении нужно экранирование перед точкой и тире.

---

core/libraries/filter.php
Метод filename повторяет такой же из make_safe_name

---

core/libraries/folder.php
return (bool) (self::exists && is_writable($location)) - я думаю недописал просто

---

mkdir выдаст варнинг если не сможет создать директорию

---

get_safe_name опять повтор

---

core/libraries/hit.php
в методе add_obj есть crc32( $class_name ) и оно вставляется в столбик ID, црц может быть отрицательным
а столбик unsigned. Надо бы делать abs или еще как.

---

core/libraries/image.php
Используется is_file вместо системного, можно по идее просто поискать по всем исходникам по именам таких вот
замененных функций, наверняка еще найдется.

---

core/libraries/metainfo.php
До сих пор используется loadObjectList, setQuery надо бы еще просто весь код пошерстить на предмет наличия таких функций
ну и нужна ли такая функция, которая использует такие устаревшие вызовы.

---

core/libraries/randomizer.php
$hash[] = $symbols{mt_rand(0, $symbols_length)}; а потом делаем implode('', $hash);
не проще ли сразу собирать в строку. Да и зачем нужен класс ради одной функции, может стоит вынести это куда-нибудь

---

core/libraries/text.php
joosText::pretty_date подозрительно похож на joosDateTime::time_ago

**Comment by xboston** [comment]
exception_if_file_not_exists - готово
make_safe_name - готово
filter.php - готово
folder.php - готово
get_safe_name - там разная логика очистки названия каталога и файла
randomizer - склейка длинных строк через массив быстрее чем через точку, класс с функцией будет расширен
pretty_date - убрал

Сделано в коммите adf5eeecaee06c125e66aad4fa1e70844607a361

**Comment by xboston** [comment]
Добил остальные. Использование функций библиотек в системе дело ответсвенное, вносится поэтапно ;)
