### ISSUE TITLE
Еще замечания по коду

### ISSUE THREAD

**Issue by deadkrolik** [joostina/joostina#99]
Скачал только что самую-самую последнюю версию. Вот что дополню или повторю из предыдущего:

---

is_file - найдена в очень многих местах, надо избавляться от нее. Тоже про readable.

---

название joosCore::admin не говорит вообще ни о чем

---

одинаковые по смыслу вещи лежат в разных местах joosPages::page403 и прочее - joosController::error404. Может надо что-то единое сделать и для аякса тоже (чтобы не использовать ajax_error404) и смотреть откуда пришел клиент.

---

метод prepare_modules_for_current_page не используется

---

есть функция function __($string, array $args = null), но все равно везде используется sprintf. Хотя может было бы логичнее использовать функцию с переменным числом параметров и все вхождения %s по порядку заменять. Что бы не заморачиваться с array(...)

---

JUSER_NAME_REGEX нет экранирования перед тире

---

mosSmartSubstr какая-то некромантия с префиксом

---

to_canonikal - рускаво языка - to_canonical

---

зачем нужно joosSession::get + set если в коде иногда напрямую используется массив $_SESSION

---

Для отдачи заголовков неплохо бы использовать одну единую фукнцию, например send_headers_by_code, сейчас по всему коду раскиданы пхп'шные header()

---

get_all_meta_items не используется по-моему

---

Класс Thumbnail генерирует user_error, как-то не очень это все

**Comment by xboston** [comment]
- is_file заменено на joosFile::exist
- readable заменено на joosFile::is_readable
- joosCore::admin переименовано в joosCore::set_admin_mode , это кандидат на удаление, пока не удалось красиво разрулить сессии админки и сайта
- joosController::error404 устранено, использовано joosPages::page404, для ajax режима надо развернуть какой-либо боевой проект и посмотреть какое решение себя лучше покажет
- работа с модулями удалена из внутренностей ядра
- JUSER_NAME_REGEX- экранирование добавлено
- mosSmartSubstr вернулось в небытие, прихватив с собой amp_replace
- to_canonical облагорожено
- с joosSession та же тема что и с сессиями в админке и на сайте, как получится их корректно разделить - код обновится, пока страшно наживую менять
- для установки header добавлена функция joosRequest::send_headers
- весь кода Metainfo убран в чулан
- user_error заменены на joosImageLibrariesException

Про функцию sprintf и __ расскажи пожалуйста подробнее

**Comment by deadkrolik** [comment]
Ну смотри, по сути эти две функции занимаются одним и тем же - заменой элементов в подстроке на указанные по порядку. Так может написать еще одну, которая будет
а) заменять элементы, только заранее определенные
б) не будет требовать громоздких конструкций array('a' => адынадын, 'b' => 'тватва')

**Comment by deadkrolik** [comment]
И ты убрал метаинфо в чулан. А вот компонент metainfo может тоже туда?

**Comment by xboston** [comment]
Отличный план, дочищу metainfo!

ПАро замену в строках хотелось бы более конкртеный пример, важно что бы разработчику было понятно что на что заменится, не было регулярок и не надо было высчитывать и помнить позицию элемента для замены

**Comment by deadkrolik** [comment]
Ишь ты какой, без регулярок. Святым духом что ли искать подстроки? Я вижу это примерно так: http://www.php.net/manual/ru/function.func-get-args.php#89741

**Comment by xboston** [comment]
Неее, это уже не круто. Получается зависимость переменной от местоположения, поменяли в строке слова местами - надо и во всех локализациях менять, и параметры передаваемые в цункцию по местам расставлять. не, не круто
